meta_product_name: "The Comic Strip Generator"
meta_title: "The Comic Strip Generator"
meta_description: "This is a comic strip generator where you can blend panels from old comics or even add your own strip to increase the generator's possibilities."
meta_image: "cover.png"
